# BraTS Glioma Segmentation Training Configuration

experiment_name: 'brats_unet3d_v1'
output_dir: './experiments'

# Data configuration
data:
  raw_dir: r'C:\Projects\BIG_DATA\BIG_DATA\data\raw\training_data1_v2'
  processed_dir: r'C:\Projects\BIG_DATA\BIG_DATA\data\processed'
  splits_dir: r'C:\Projects\BIG_DATA\BIG_DATA\data\splits'
  patch_size: [128, 128, 128]  # [D, H, W]

# Model configuration
model:
  name: 'unet3d'  # Options: 'unet3d', 'attention_unet3d'
  in_channels: 4  # T1, T1Gd, T2, FLAIR
  num_classes: 5  # Background + 4 tumor regions
  base_channels: 32
  depth: 4

# Training configuration
training:
  num_epochs: 300
  batch_size: 2  # Adjust based on GPU memory
  num_workers: 4
  
  # Loss function
  loss: 'combined'  # Options: 'dice', 'combined', 'focal'
  dice_weight: 0.5
  ce_weight: 0.5
  
  # Optimizer
  optimizer:
    name: 'adamw'
    lr: 0.0001
    weight_decay: 0.0001
  
  # Learning rate scheduler
  scheduler:
    name: 'cosine'  # Options: 'cosine', 'reduce_on_plateau'
    min_lr: 0.000001
  
  # Gradient clipping
  gradient_clip: 1.0
  
  # Checkpoint saving
  save_freq: 10  # Save checkpoint every N epochs
  
  # Multi-GPU training
  use_multi_gpu: true

# Validation configuration
validation:
  eval_freq: 1  # Evaluate every N epochs
  
# Augmentation configuration
augmentation:
  enabled: true
  horizontal_flip: 0.5
  rotation: 15  # degrees
  brightness_contrast: 0.2
  gamma: 0.5
  gaussian_noise: 0.3

# Inference configuration
inference:
  patch_size: [128, 128, 128]
  patch_overlap: [16, 16, 16]  # Overlap for sliding window
  batch_size: 4
  tta: false  # Test-time augmentation